### ISSUE TITLE
Shortcuts pane is covered by other panes - must have z-index:3

### ISSUE THREAD

**Issue by ethernal** [akalajzi/atom-file-bookmark#21]
The properties:

`.file-bookmark .file-bookmark-icons.panel-open` and
`.file-bookmark .file-bookmark-icons.panel-closed` 

should have high enough z-index to be clickable when they overflow over another plugin. In my case it's [document-outline](https://atom.io/packages/document-outline) package.  Since DO uses z-index:2 on the pane it might make sense to set z-index to at least 3 as a workaround. It may make sense to remove z-index from DO, but that requires discussion with the DO author @mangecoeur.

You might also want to switch to a more standard tool-bar support instead of custom floating buttons.

I added an Issue to document-outline package as well: https://github.com/mangecoeur/document-outline/issues/27 so we can discuss it.

As far as I am concerned I'd opt to remove z-index from document-outline as this seems to be a non standard use and this will bring trouble when everyone starts abusing this property unless it's absolutely required.

**Comment by akalajzi** [comment]
I can add z-index, but that kind of practice might as well start z-index wars.
I agree that icon toggles are probably not positioned in the best possible way, but thats mostly because there's no real toolbar in out-of-the-box atom. I expected some other plugins might take that space, so having icons is optional in file-bookmark. Everything is reachable through regular actions, or custom shortcuts.
